### ISSUE TITLE
Finalizar Orden

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#28]
Finalizar la orden es pasarla al estado de finished. NO solo se pueden finalizar la orden si hay algún orderProduct en estado pending, se debe generar una excepción de negocio si no se puede finalizar.

**Comment by SebastianObando** [comment]
![Finalizar orden](https://user-images.githubusercontent.com/42673790/93830978-46d53480-fc37-11ea-97e3-727f4c0fe0c7.jpg)

**Comment by SebastianObando** [comment]
![Finalizar orden (1)](https://user-images.githubusercontent.com/42673790/94210397-3968b600-fe94-11ea-8537-405bb1a31c22.jpg)
