### ISSUE TITLE
Crear producto

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#29]
para crear el productStore se debe validar que el producto exista, la tienda exista la categoria exista, si no se cumple nada de lo anterior se debe generar una excepción de negocio

**Comment by CesarPava** [comment]
![Diseño software-productStore](https://user-images.githubusercontent.com/69518232/93834823-cf0d0700-fc42-11ea-925f-c18275c42211.png)

**Comment by CesarPava** [comment]
![Diseño software-productStore](https://user-images.githubusercontent.com/69518232/94346762-69c76600-fff4-11ea-8204-fed66682f2e1.png)
