### ISSUE TITLE
Crear categoria

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#30]
Para crear una cateogiria se debe validar
1. el nombre de una categoria para una misma tienda no se debe repetir
2. la tienda debe existir

si no se cumple lo anterior se debe generar una excepción de negocio.

**Comment by CesarPava** [comment]
![Diseño software-category](https://user-images.githubusercontent.com/69518232/93834799-bf8dbe00-fc42-11ea-9d10-f8561a65a552.png)

**Comment by CesarPava** [comment]
![Uploading Diseño software-category.png…]()

**Comment by CesarPava** [comment]
![Diseño software-category](https://user-images.githubusercontent.com/69518232/94346776-7ea3f980-fff4-11ea-9ff8-5906a942abed.png)
