### ISSUE TITLE
Quitar producto de la orden

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#31]
Marcar el order producto como **removed**, solo se puede marcar como **removed** un order_product que este en estado **pending** o estado **checked**

Se debe validar si el order product si pertenece a la orden que se quiere eliminar, si no se cumple esto se debe generar una excepción de negocio.

se debe actualizar el atributo totalValue de la orden.

pueden pasar varias cosas si se elimina un producto:

1. si se elimina el producto y todos los otros productos estan en removed la orden se debe actualizar a un estado **canceled**

2. si se elimina un producto y es el unico producto de la orden se debe marcar la orden como cancelada

**Comment by Jeronimo90-eng** [comment]
![DisenioSoftJeronimoRobledo](https://user-images.githubusercontent.com/69558043/93848522-6c7e3000-fc6f-11ea-909d-92c9f317fce7.png)

**Comment by Jeronimo90-eng** [comment]
![DisenioSoftJeronimoRobledo (1)](https://user-images.githubusercontent.com/69558043/93848642-cf6fc700-fc6f-11ea-8701-8ee1b460f273.png)

**Comment by Jeronimo90-eng** [comment]
![DisenioSoftJeronimoRobledo (2)](https://user-images.githubusercontent.com/69558043/94234326-17405980-fecf-11ea-9236-219454472978.png)
