### ISSUE TITLE
Check product

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#32]
Solo se debe marcar un orderProduct como **checked** si este esta en estado **pending**. si no se cumple esto se debe generar una excepción de negocio
se debe verificar que exista el orderProduct, si no existe se debe lanzar una excepción de negocio

**Comment by SebastianObando** [comment]
![Check Product](https://user-images.githubusercontent.com/42673790/93831004-5785aa80-fc37-11ea-826c-5718819e28d0.jpg)

**Comment by SebastianObando** [comment]
![Check Product (1)](https://user-images.githubusercontent.com/42673790/94210410-4685a500-fe94-11ea-950c-1d23afebb99f.jpg)
