### ISSUE TITLE
Agregar producto a orden

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#33]
solo se puede agregar un producto a la orden si este producto no esta en la orden, si el producto ya esta en la orden se deben aumentar el numero de unidades que ya tenia, es decir si se quiere agregar un cocacola y ya en la orden había 2 cocacola, no se debe agregar un nuevo orderProdiuct si no que el que ya esta debe quedar en 3 unidades.

se debe validar que el producto si exista y que pertenezca a la tienda de la orden, en caso de fallar esto se debe generar una excepción de negocio.

se debe actualizar el atributo totalValue de la orden.

tampoco se puede agregar un producto si el total del producto (precio por cantidad) supera el 10% del total de la orden, si esto pasa se debe generar una excepción de negocio.

**Comment by INGJOSEHV** [comment]
![DiseñoBD](https://user-images.githubusercontent.com/69516521/93837072-76416c80-fc4a-11ea-9b00-a6b512d5f866.png)

**Comment by INGJOSEHV** [comment]
![DiseñoBD (1)](https://user-images.githubusercontent.com/69516521/94230964-b01fa680-fec8-11ea-9c59-e86fd2546da1.png)
