### ISSUE TITLE
Quitar producto de carrito de compra

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#35]
borrar el registro del ShoppingCartProduct. si el producto que se borra es el ultimo del carrito se debe borrar el carrito tambien.

validar que el shoppingcartProduct si exista, si no existe se debe generar una excepcion de negocio

**Comment by GilberttValentine** [comment]
![Diagrama de flujo](https://user-images.githubusercontent.com/69516529/93804999-aff38280-fc0c-11ea-80db-7f63b6a22c5a.jpg)

**Comment by GilberttValentine** [comment]
![Diagrama de flujo](https://user-images.githubusercontent.com/69516529/94209473-0b827200-fe92-11ea-9b11-7753c4eb32c8.jpg)
