### ISSUE TITLE
Agregar producto a carrito de compra

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#36]
Para agregar un producto a un carrito se debe enviar el id de la tienda y el id del usuario y el id del producto y la cantidad, si no hay un carrito para el usuario en esa tienda se debe crear un carrito de compra para ese usuario en esa tienda, si ya existe el carrito el producto se debe agregar a dicho carrito ya existente.

se debe validar que el producto que se quiere agregar si exista en la tienda, si no, se debe lanzar una excepción de negocio.

**Comment by Filowannabe** [comment]
[Felipe Corredor-Diagramas.docx](https://github.com/eamquindio/diseno2020_2-mitienda-backend/files/5257409/Felipe.Corredor-Diagramas.docx)

**Comment by caferrerbeam** [comment]
el diagrama como imagen porfa

**Comment by Filowannabe** [comment]
![FelipeCorredorDiagram](https://user-images.githubusercontent.com/69178655/93805864-eaa9ea80-fc0d-11ea-8c17-542d890b2914.jpg)

**Comment by Filowannabe** [comment]
![FelipeCorredorDIagram](https://user-images.githubusercontent.com/69178655/94196652-4ed0e680-fe7a-11ea-86af-dd4bba4ee98f.jpg)

**Comment by Filowannabe** [comment]
![FInalDiagramFelipe](https://user-images.githubusercontent.com/69178655/94581557-d9319580-0240-11eb-9ea3-2afbc96bb521.jpg)
