### ISSUE TITLE
Iniciar sesion tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#37]
para iniciar la sesión en la tienda se debe suministrar el correo y el password, como el password en la BD esta encriptado, se debe encriptar el password que el usuario suministra para iniciar sesión y comparar los password en su forma encriptada. si falla el correo o el password se debe generar una excepción de negocio

**Comment by CristhianCAM** [comment]
![inicio sesion tienda](https://user-images.githubusercontent.com/69518355/94204529-05d35f00-fe87-11ea-9029-f2adba02927f.png)
