### ISSUE TITLE
Iniciar sesion usuario

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#38]
para iniciar la sesión en el usuario se debe suministrar el username y el password, como el password en la BD esta encriptado, se debe encriptar el password que el usuario suministra para iniciar sesión y comparar los password en su forma encriptada. si falla el usuario o el password se debe generar una excepción de negocio

**Comment by saralucia1224** [comment]
![Uploading Tarea Diseño de Software-Iniciar Sesión Usuario.png…]()

**Comment by saralucia1224** [comment]
![Tarea Diseño de Software-Iniciar Sesión Usuario](https://user-images.githubusercontent.com/69540198/93832185-8cdfc780-fc3a-11ea-95ed-49b991accedf.png)

**Comment by saralucia1224** [comment]
![Tarea Diseño de Software-Iniciar Sesión Usuario](https://user-images.githubusercontent.com/69540198/93945713-12c44700-fcfd-11ea-9825-df54ef3bbb27.png)
