### ISSUE TITLE
Registrar tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#39]
las reglas para registrar una tienda son:
1. no se puede crear una tienda con un correo que ya exista ni con un nombre que ya existe, si no se cumple esto, se debe generar una excepción de negocio

2. el password de la tienda se debe encriptar en MD5 y se debe guardar asi en la BD: https://www.yoelprogramador.com/como-encriptar-contrasenas-en-md5-en-java/

**Comment by CristhianCAM** [comment]
![CREAR TIENDA (1)](https://user-images.githubusercontent.com/69518355/94204579-1f74a680-fe87-11ea-933d-6a0a228c8436.png)
