### ISSUE TITLE
Registrar usuario

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#40]
no se puede crear un usuario con un correo que ya exista ni con un usuario que ya existe, si no se cumple esto, se debe generar una excepción de negocio

el password del usuario se debe encriptar en MD5 y se debe guardar asi en la BD: https://www.yoelprogramador.com/como-encriptar-contrasenas-en-md5-en-java/

**Comment by saralucia1224** [comment]
![Tarea Diseño de Software-Registrar un Usuario](https://user-images.githubusercontent.com/69540198/93832097-42f6e180-fc3a-11ea-88aa-fcdee1e84665.png)

**Comment by saralucia1224** [comment]
![Tarea Diseño de Software-Registrar un Usuario](https://user-images.githubusercontent.com/69540198/93945604-e1e41200-fcfc-11ea-8cbb-60ecbe912a97.png)
