### ISSUE TITLE
API remover producto

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#56]
url:/ order-products/{orderProductId}
verb : DELETE
parametros: Query param ?product_Id = .product_Id
Body {"status": 200,
"order": order (objeto)
}

**Comment by caferrerbeam** [comment]
URL: /orders/{orderId}/order-product/{orderProductId}
Verb: DELETE
REturn la orden.

**Comment by CristhianCAM** [comment]
listo 👍
