### ISSUE TITLE
API borrar producto del shopping cart

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-backend#65]
url:/ shopping-cart/{id_shopping_cart}/shopping-cart-product/{id-shopping-cart-product}
verbo : DELETE
parametros: Query param ?id_shopping_cart= .id-shopping-cart-product
Body {"status": 200,
"shoppingcardproduct": shoppingcardproduct (objeto)
}

**Comment by caferrerbeam** [comment]
URL: /shopping-cart/{id_shopping_cart}/shopping-cart-product/{id-shopping-cart-product}
Parametros: path params
Return 200ok

**Comment by CristhianCAM** [comment]
corregido 👍
